repos:
  - repo: https://github.com/crate-ci/typos
    rev: v1.45.0
    hooks:
      - id: typos
        pass_filenames: false
  - repo: local
    hooks:
      - id: fmt
        name: cargo fmt
        entry: cargo fmt --all --check
        language: system
        pass_filenames: false
      - id: clippy
        name: cargo clippy
        entry: cargo clippy --all-targets -- -D warnings
        language: system
        pass_filenames: false
